const styles = (theme) => ({
  submitLayout: {
    backgroundColor: theme.palette.common.white,
    borderRadius: 7,
    boxShadow: '0px 1px 10px 0px rgba(0,0,0,0.2)',
    marginTop: theme.spacing(4),
    height: 120,
    position: 'relative',
    right: -4,
    width: '98%',
    zIndex: 2,

    '&:after': {
      backgroundColor: theme.palette.common.white,
      bottom: 105,
      boxShadow: '0px 1px 10px 0px rgba(0,0,0,0.2)',
      content: "' '",
      height: 30,
      position: 'absolute',
      right: 49,
      transform: 'rotate(45deg)',
      width: 30,
      zIndex: -1,
    },
  },
  submitInnerWrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    backgroundColor: theme.palette.common.white,
    borderRadius: 10,
    height: '100%',
    width: '100%',
    padding: '16px 16px 32px',
  },
  formHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '100%',
  },
  closeIconButton: {
    color: theme.palette.text.disabled,
    paddingBottom: theme.spacing(0),
    paddingRight: theme.spacing(0),
    paddingTop: theme.spacing(0),

    '&:hover': {
      backgroundColor: 'transparent',
    },
  },
  enquiryFormlayout: {
    backgroundColor: theme.palette.common.white,
    borderRadius: 7,
    boxShadow: '0px 1px 10px 0px rgba(0,0,0,0.2)',
    marginTop: theme.spacing(4),
    minHeight: 200,
    position: 'relative',
    right: -4,
    width: '98%',
    zIndex: 2,

    '&:after': {
      backgroundColor: theme.palette.common.white,
      bottom: 199,
      boxShadow: '0px 1px 10px 0px rgba(0,0,0,0.2)',
      content: "' '",
      height: 30,
      position: 'absolute',
      right: 49,
      transform: 'rotate(45deg)',
      width: 30,
      zIndex: -1,
    },
  },
  errorEnquiryFormlayout: {
    backgroundColor: theme.palette.common.white,
    borderRadius: 7,
    boxShadow: '0px 1px 10px 0px rgba(0,0,0,0.2)',
    marginTop: theme.spacing(4),
    minHeight: 200,
    position: 'relative',
    right: -4,
    width: '98%',
    zIndex: 2,

    '&:after': {
      backgroundColor: theme.palette.common.white,
      bottom: 223,
      boxShadow: '0px 1px 10px 0px rgba(0,0,0,0.2)',
      content: "' '",
      height: 30,
      position: 'absolute',
      right: 49,
      transform: 'rotate(45deg)',
      width: 30,
      zIndex: -1,
    },
  },
  enquiryFormInnerWrapper: {
    backgroundColor: theme.palette.common.white,
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    padding: theme.spacing(2),
    width: '100%',
  },
  formHeaderText: {
    display: 'flex',
    flexDirection: 'column',
  },
  headerText: {
    color: theme.palette.text.medium,
    fontSize: theme.typography.fontSize * 0.9,
    fontWeight: 500,
  },
  enquiryFormTextField: {
    fontSize: theme.typography.fontSize * 0.9,
  },
  buttonWrapper: {
    display: 'flex',
    spaceDirection: 'row',
    justifyContent: 'space-between',
  },
  cancelButton: {
    boxShadow: 'none',
    color: theme.palette.text.medium,
    fontSize: theme.typography.fontSize * 0.7,
    height: 36,
    letterSpacing: 1.1,
  },
  submitButton: {
    boxShadow: 'none',
    height: 36,
    letterSpacing: 1.1,
    width: 95,
  },
  errorWrapper: {
    alignItems: 'center',
    display: 'flex',
  },
  errorIcon: {
    color: 'red',
    marginRight: theme.spacing(1),
  },
  errorText: {
    color: 'red',
    fontSize: theme.typography.fontSize * 0.7,
    fontStyle: 'italic',
    textTransform: 'uppercase',
  },
});

export default styles;
