// ui
export const ENQUEUE_NOTIFICATION = 'ENQUEUE_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const UPDATE_THREE_D_PRODUCT_ID = 'UPDATE_THREE_D_PRODUCT_ID';

// common
export const SET_SETTINGS = 'SET_SETTINGS';
export const SET_CURRENCY = 'SET_CURRENCY';
export const TOGGLE_CART_SIDE_BAR = 'TOGGLE_CART_SIDE_BAR';
export const SET_SAVED_URL = 'SET_SAVED_URL';
export const SET_CURRENCY_RATES = 'SET_CURRENCY_RATES';
export const SET_SYSTEM_GST = 'SET_SYSTEM_GST';

// user
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_REGISTER_USER_DETAILS = 'SET_REGISTER_USER_DETAILS';
export const SET_REQUEST_ROLE_DETAILS = 'SET_REQUEST_ROLE_DETAILS';

// merchant
export const SET_MERCHANT_PROFILE = 'SET_MERCHANT_PROFILE';

// product
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const SET_PRODUCT_CATEGORY_LIST = 'SET_PRODUCT_CATEGORY_LIST';
export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';
export const SET_PRODUCT_VARIANT = 'SET_PRODUCT_VARIANT';
export const SET_PRODUCT_OPTION = 'SET_PRODUCT_OPTION';
export const SET_PRODUCT_PROMOTION_DETAILS = 'SET_PRODUCT_PROMOTION_DETAILS';
export const SET_PRODUCT_REVIEW_SUMMARY = 'SET_PRODUCT_REVIEW_SUMMARY';

// listing
export const CLEAR_LISTING = 'CLEAR_LISTING';
export const SET_LISTING_PAGE = 'SET_LISTING_PAGE';
export const SET_LISTING_SEARCH = 'SET_LISTING_SEARCH';
export const SET_LISTING_FILTER = 'SET_LISTING_FILTER';
export const SET_LISTING_PARAMS = 'SET_LISTING_PARAMS';
export const SET_ON_SALE_LIST = 'SET_ON_SALE_LIST';
export const SET_FEATURED_PRODUCT_LIST = 'SET_FEATURED_PRODUCT_LIST';
export const SET_MERCHANT_RECOMMEND_LIST = 'SET_MERCHANT_RECOMMEND_LIST';
export const SET_CATEGORY_RECOMMEND_LIST = 'SET_CATEGORY_RECOMMEND_LIST';

export const SET_FEATURED_GLOBAL_LIST = 'SET FEATURED GLOBAL LIST';
export const SET_FEATURED_INHOUSE_LIST = 'SET FEATURED INHOUSE LIST';
export const SET_FEATURED_SETTING_LIST = 'SET FEATURED SETTING LIST';
export const SET_FEATURED_GEMSTONE_LIST = 'SET FEATURED GEMSTONE LIST';

// transaction
export const SET_TRANSACTION_CART = 'SET_TRANSACTION_CART';
export const SET_DELIVERY_OPTIONS = 'SET_DELIVERY_OPTIONS';
export const SET_TRANSACTION_FILTER_DURATION = 'SET_TRANSACTION_FILTER_DURATION';
export const UPDATE_TRANSACTION_FILTER = 'UPDATE_TRANSACTION_FILTER';

// favourite
export const TOGGLE_FAVOURITE_MODAL = 'TOGGLE_FAVOURITE_MODAL';
export const SET_TOTAL_FAVOURITE_ITEM = 'SET_TOTAL_FAVOURITE_ITEM';

// compare products
export const SET_COMPARE_LISTING = 'SET COMPARE LISTING';
export const ADD_TO_COMPARE_LIST = 'ADD TO COMPARE LIST';
export const REMOVE_TO_COMPARE_LIST = 'REMOVE TO COMPARE LIST';

// build a ring
export const SET_BUILD_RING_SETTING = 'SET BUILD RING SETTING';
export const SET_BUILD_RING_DIAMOND = 'SET BUILD RING DIAMOND';
export const SET_BUILD_RING_FINAL = 'SET BUILD RING FINAL';
export const CLEAR_BUILD_RING = 'CLEAR BUILD RING';
